#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <security/pam_modules.h>

PAM_EXTERN int pam_sm_authenticate(pam_handle_t *pamh, int flags, int argc, const char **argv){
    const char *user_input;
    int retval;

    const char *inputtedName;
    char charactersInLine[1000], username[50], secretKey[17], totpCode[6];
    int inputtedCode;

    // The variable 'username' receives the value entered in the 'Username' field belonging to the login.
    retval = pam_get_user(pamh, &inputtedName, "Username: ");
    if(retval != PAM_SUCCESS || inputtedName == NULL){
        return PAM_AUTH_ERR;
    }
    if(strcmp(inputtedName, "root") == 0){
    /*
        Here, the root can define their secretKey.
        'JBSWY3DPEHPK3PXP' is a default key!
        The root needs to register this secretKey with Google Authenticator or on the website.
    */
        strcpy (secretKey, "JBSWY3DPEHPK3PXP");
    }else{
        // The 'secretKey' is retrieved from the file by comparing the entered name with the names present in 'secretKeyList.txt'.
        FILE *file = fopen("/root/secretKeyList.txt","r");

        if(file == NULL){
            printf("\n\n Error opening the file!");
            return 1;
        }

        while(fgets(charactersInLine,1000,file) != NULL){
            if(sscanf(charactersInLine, "username: %s secretKey: %s", username, secretKey) == 2){
                if(strcmp(username, inputtedName) == 0){
                    break;
                }
            }
        }
        fclose(file);
    }

    // The user will input the TOTP code generated by Google Authenticator
    printf("\nInput your TOTP code: ");
    scanf("%i",&inputtedCode);

    // The 'secretKey' will be sent to 'TOTPgenerator.py' using a PIPE
    FILE *pipe;

    pipe = popen("python3 /root/TOTPgenerator.py","w");
    fprintf(pipe,"%s",secretKey);
    fflush(pipe);
    pclose(pipe);

    /*
      The TOTP code is saved in a temporary file by 'TOTPgenerator.py',
        the snippet below accesses the file, assigns its content to the variable 'totpcode'
        and deletes the file.
    */

    FILE *fileKey = fopen("/root/key.txt","r");
    fscanf(fileKey,"%s",totpCode);
    fclose(fileKey);
    remove("/root/key.txt");

    int totp = atoi(totpCode);

    // 'totp' and 'inputtedCode' will be compared to validate access.
    if(inputtedCode == totp){
        printf("\n\n Authorized access!\n\n");
        return PAM_SUCCESS;
    }else{
        printf("\n\n Access denied!\n\n");
        return PAM_AUTH_ERR;
    }
}


PAM_EXTERN int pam_sm_setcred(pam_handle_t *pamh, int flags, int argc, const char **argv) {
    return PAM_SUCCESS;
}


